checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  environment:
    php:
      version: 8.0.15
      ini:
        xdebug.mode: coverage

    variables:
      COMPOSER_ROOT_VERSION: 'dev-dev'

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      services:
        db-mysql:
          image: mysql:5.7

          # Define any additional environment variables that are needed by the service.
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: 'yiitest'

      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
