checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  environment:
    php:
      version: 8.0.18
      ini:
        xdebug.mode: coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      services:
        db-mysql:
          image: mysql:8.0.29

          # Define any additional environment variables that are needed by the service.
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: yiitest

          # We automatically forward these ports from your localhost to the service's port.
          # Alternatively, you can also access the service on the "$SERVICE_SOME_NAME_IP"
          # environment variable.
          ports:
            # Forward 127.0.0.1:12345 -> SERVICE_IP:12345
            - 3306

          # If your service writes data to disk like most databases do, you can significantly
          # speed up tests by mounting a ramdisk at those paths.
          ramdisks:
            - /var/lib/data

      dependencies:
        override:
          - composer self-update
          - composer config preferred-install.yiisoft/db source
          - composer update --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
