services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: yiitest
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3306:3306
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
