version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/setup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: yii

  web:
    build: ./php
    depends_on:
      - db
    volumes:
      - ./../:/var/www/html/
    ports:
      - "8100:80"
