on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ansi-mode.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

  push:
    branches: ['master']
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ansi-mode.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

name: ansi-mode

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.mysql }}

    env:
      COMPOSER_ROOT_VERSION: 1.0.0
      EXTENSIONS: pdo, pdo_mysql

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 8.5

        mysql:
          - mysql:9
        include:
          - mysql: mysql:9
            mysql_image: mysql:9@sha256:ad88e1c86cbf12ef52d0a0360cd4b774d22956c5ee9c565645fb019d7aacb6c3

    services:
      mysql:
        image: ${{ matrix.mysql_image }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: ''
          MYSQL_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --name=mysql_ansi --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Change mysql sql_mode.
        run: docker exec mysql_ansi mysql -u root -e "SET GLOBAL sql_mode = 'ANSI';"

      - name: Checkout.
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Update composer.
        run: composer self-update

      - name: Install db.
        uses: yiisoft/actions/install-packages@master
        with:
          packages: >-
            ['db']

      - name: Run tests with phpunit with code coverage.
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@04b047e8bb82a0c002c8312c1c880fbc6a999d45
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
