on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build-mariadb.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

  push:
    branches: ['master']
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build-mariadb.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

name: build-mariadb

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.mariadb }}

    env:
      COMPOSER_ROOT_VERSION: 1.0.0
      EXTENSIONS: pdo, pdo_mysql
      YII_MYSQL_TYPE: 'mariadb'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.5

        mariadb:
          - mariadb:10.4
          - mariadb:10.5
          - mariadb:10.6
          - mariadb:10.7
          - mariadb:10.8
          - mariadb:10.9
          - mariadb:12

        include:
          - php: 8.5
            mariadb: mariadb:10.4
            mariadb_image: mariadb:10.4@sha256:22edfe1c78349f8cae88bbb5c2873b7e6c515be767c91c691308ce57445806f3
          - php: 8.5
            mariadb: mariadb:10.5
            mariadb_image: mariadb:10.5@sha256:a530aeeefd82f4fa5150f391b6c75462140904780338766f6b03acecb1cca3ce
          - php: 8.5
            mariadb: mariadb:10.6
            mariadb_image: mariadb:10.6@sha256:daacc2f260f8ec999daa5e03a017a23a7e6fa3fb982aaf26e8b72f24daf03bc9
          - php: 8.5
            mariadb: mariadb:10.7
            mariadb_image: mariadb:10.7@sha256:9a48ac9f196f3d4fd6fea2cab59a49df9e7ca459bf14b2f7b85a0e38a5454571
          - php: 8.5
            mariadb: mariadb:10.8
            mariadb_image: mariadb:10.8@sha256:456709ab146585d6189da05669b84384518baecd83670c9e5221f8c20a47cf1e
          - php: 8.5
            mariadb: mariadb:10.9
            mariadb_image: mariadb:10.9@sha256:56710811b0b96233ef84f4982d3337d88d3aa46a68f3fcb2853b94e1d04ea25c
          - php: 8.5
            mariadb: mariadb:12
            mariadb_image: mariadb:12@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
          - php: 8.1
            mariadb: mariadb:12
            mariadb_image: mariadb:12@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
          - php: 8.2
            mariadb: mariadb:12
            mariadb_image: mariadb:12@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
          - php: 8.3
            mariadb: mariadb:12
            mariadb_image: mariadb:12@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
          - php: 8.4
            mariadb: mariadb:12
            mariadb_image: mariadb:12@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b

    services:
      mysql:
        image: ${{ matrix.mariadb_image }}
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_ROOT_PASSWORD: ''
          MARIADB_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Update composer.
        run: composer self-update

      - name: Install db.
        uses: yiisoft/actions/install-packages@master
        with:
          packages: >-
            ['db']

      - name: Run tests with phpunit with code coverage.
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
